# Snapshot capturing period in seconds
time_period_sec: 3600
# Number of worker processes to capture snapshots
workers: 2

ffmpeg:
  # FFMPEG executable path
  bin: 'ffmpeg'
  # Snapshot jpeg compression, effective range 2-31, 2 - best quality, 31 - worst
  jpeg_compression: 5
  # Snapshot capturing timeout in seconds
  timeout_sec: 300

env:
  # Used for logging and timestamp to date resolution
  timezone: 'Europe/Moscow'

# Inline cameras configuration
cameras:
  # Configuration format:
  # - !!python/object:webcam.Camera
  #   name: camera name
  #   uri: camera uri

# Load cameras configuration from m3u8 file.
# If at least one camera is configured inline, then this property is ignored.
# Not recommended unless you have control over playlist m3u8 file generation.
#
# Supported format:
#  #EXTM3U
#  #EXT-X-SESSION-DATA:DATA-ID="camera.name",VALUE="My Camera 1"
#  #EXT-X-STREAM-INF:...
#  http://video.url/camera.m3u8
#
cameras_playlist: 'cameras.m3u8'

# Amazon S3 properties
s3:
  # All images will be saved to this bucket
  bucket_name: '(secret)'
  access_key: '(secret)'
  secret_key: '(secret)'