time_period: 10
workers: 2

ffmpeg:
  bin: 'ffmpeg'
  jpeg_compression: 5
  timeout_sec: 30

env:
  timezone: 'Europe/Moscow'

cameras:
- !!python/object:webcam.Camera
  name: '23'
  uri: 'http://video03.setl.ru/status_1/index.m3u8'
- !!python/object:webcam.Camera
  name: '12'
  uri: 'http://video03.setl.ru/status_4/index.m3u8'
- !!python/object:webcam.Camera
  name: '1_34'
  uri: 'http://video03.setl.ru/status_2/index.m3u8'
- !!python/object:webcam.Camera
  name: '1_56'
  uri: 'http://video03.setl.ru/status_3/index.m3u8'

s3:
  bucket_name: '(secret)'
  access_key: '(secret)'
  secret_key: '(secret)'